### ISSUE TITLE
`CONTRIBUTING.md` does not exist

### ISSUE THREAD

**Issue by junyang-chin** [data-gov-my/datagovmy-front#279]
CONTRIBUTING.md does not exist in https://github.com/data-gov-my/datagovmy-front/blob/9c127a0c8c24a97c87d0945da116a1a5df57010a/apps/docs/README.md?plain=1#L9C1-L9C1

**Comment by irfancoder** [comment]
Thanks, we overlooked this bit. The team will write one up in the near future

**Comment by amalasyrafs** [comment]
Hi @junyang-chin , thanks for notifying this to our team. The CONTRIBUTING.md shouldn't be there and we have properly adjusted the README to properly link the Contribution.

Refer to #365 

Thanks for alerting us!
