### ISSUE TITLE
Download option in dashboard front-end

### ISSUE THREAD

**Issue by philip-khor** [data-gov-my/datagovmy-front#295]
Dashboards currently lack a download option for the underlying data, many (if not all) of which are not available in the data catalogue (or from a cursory glance at the docs, not via API endpoints either). 

May be relevant: https://github.com/dosm-malaysia/kawasanku-front/issues/44

**Comment by data-gov-my** [comment]
This feature will not be added - all underlying data (higher granularity and frequency than presented on the dashboard) will be available via the DC in due course.
