### ISSUE TITLE
Broken link for CPI publication

### ISSUE THREAD

**Issue by philip-khor** [data-gov-my/datagovmy-front#296]
CPI items in the data catalogue link to a dead link: 
![image](https://github.com/data-gov-my/datagovmy-front/assets/35039795/3b68a66b-bff8-4396-a5d4-c066d00ad19b)

https://storage.googleapis.com/dosm-public-publications/monthly_2023-07_cpi.pdf returns 
![image](https://github.com/data-gov-my/datagovmy-front/assets/35039795/c6cac947-2b1f-489e-8c33-c0dc2cf2e014)

Consider linking directly to DOSM's CPI release archive where they are now uploading full publications: 
- https://www.dosm.gov.my/portal-main/release-archive/da35aea1-81c8-11ed-96a6-1866daa77ef9 or perhaps 
- https://www.dosm.gov.my/portal-main/publication?search_keyword=consumer+price+index

Related; [dosm-malaysia/aksara-front](https://github.com/dosm-malaysia/aksara-front/)

**Comment by data-gov-my** [comment]
Fixed!
