### ISSUE TITLE
Broken link for filing issues on datagovmy docs

### ISSUE THREAD

**Issue by britneywwc** [data-gov-my/datagovmy-front#352]
Issue:
* The link to [leave a GitHub issue](https://github.com/data-gov-my/datagovmy-openapi/issues/new?title=500%20Internal%20Server%20Error) is broken.
* Can be found on the datagovmy **Response Code** docs [here](https://developer.data.gov.my/response-format).
<img width="717" alt="Screenshot 2023-10-20 at 5 09 23 PM" src="https://github.com/data-gov-my/datagovmy-front/assets/62298176/5131ab5d-ebc3-47da-b912-3ee951238001">

* The link to [open a new issue](https://developer.data.gov.my/faq) is broken.
* Can also be found on the datagovmy **FAQ** docs [here](https://developer.data.gov.my/faq).
<img width="732" alt="Screenshot 2023-10-20 at 5 15 57 PM" src="https://github.com/data-gov-my/datagovmy-front/assets/62298176/1e46d4d0-a88c-453b-b411-ce546c2a7aed">

**Comment by amalasyrafs** [comment]
hi @britneywwc ,

Thanks for alerting us regarding the broken links!
It was using an old implementation that we no longer use and we have amended the link accordingly so it should now be working.
