### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by razimi** [data-gov-my/datagovmy-front#363]
Im trying to replicate this onto my local. 
cannot find the lang files. Can someone point me to the location. 

Thanks.

<img width="744" alt="image" src="https://github.com/data-gov-my/datagovmy-front/assets/1865490/177e13f4-3d25-4e68-9e5d-1eb2e2144d10">

**Comment by amalasyrafs** [comment]
Hi @razimi,

For the translation file, you may add `NEXT_PUBLIC_I18N_URL` in each project's env file to our updated language files served via CDN. 

For more information, you may visit the each project README to get the value of the `NEXT_PUBLIC_I18N_URL`.
1.  [Datagovmy](https://github.com/data-gov-my/datagovmy-front/tree/main/apps/app#environment-variables)
2. [KKMNow](https://github.com/data-gov-my/datagovmy-front/tree/main/apps/kkmnow#environment-variables)
3. [OpenDOSM](https://github.com/data-gov-my/datagovmy-front/tree/main/apps/opendosm#environment-variables)

The value can also be taken in each of the project's .env.example, kindly pull from our latest code to get it reflected in your local.

Once the `NEXT_PUBLIC_I18N_URL` is set in your .env file, you should be able to properly use the language locale.

Thanks!

**Comment by razimi** [comment]
@amalasyrafs thanks for the update.
