### ISSUE TITLE
2 links got active for link 'economy' in 'Data Catalog'

### ISSUE THREAD

**Issue by razimi** [data-gov-my/datagovmy-front#368]
not sure if this is intended feature. 

clicking on the sub menu ``Economy`` will highlight another ``Economy`` menu.

 <img width="825" alt="image" src="https://github.com/data-gov-my/datagovmy-front/assets/1865490/fca21ded-78f6-4cf0-9186-94b5ff8fe787">

**Comment by amalasyrafs** [comment]
hey @razimi ,
thanks for alerting us! it is not intended and we have pushed the fix for that in #370
