### ISSUE TITLE
Feedback for “Gtfs Realtime”

### ISSUE THREAD

**Issue by cameronkyc** [data-gov-my/datagovmy-front#377]
Hi, I'm an experienced Transit Data professional and I'm happy to help testing the data, including RT-GTFS and also some active feedback on improvement for GTFS-Static. How do I go about this?

**Comment by data-gov-my** [comment]
Hi Cameron! Please write to us @ data.dtsa@mampu.gov.my with your contact details so we can connect you with the team.

We also recommend joining our Community Telegram group [here](https://t.me/datagovmy): https://t.me/datagovmy
