### ISSUE TITLE
Feedback for “Gtfs Static” - Rapid Penang GTFS

### ISSUE THREAD

**Issue by cameronkyc** [data-gov-my/datagovmy-front#378]
Hi, 

The GTFS-Static data for Rapid Penang has expired.

The range defined in calendar.txt shows that it had been expired since 5 Oct.

`service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
23092501,0,0,0,0,0,0,1,20231001,20231001
23092502,1,1,1,1,0,0,0,20231002,20231005`

**Comment by data-gov-my** [comment]
Hi Cameron! Thanks for the quick feedback - we'll look into it.

**Comment by data-gov-my** [comment]
Fixed!
