### ISSUE TITLE
Feedback for “Frequently Asked Questions”

### ISSUE THREAD

**Issue by kwongtn** [data-gov-my/datagovmy-front#386]
Hi!
Would like to suggest adding a FAQ entry detailing how to citate the data source, as currently there is none.

Thanks! 😁

**Comment by amalasyrafs** [comment]
hi @kwongtn ,
have you tried looking at our developer docs site [Docs](https://developer.data.gov.my/) ?

If this is not what you're looking for, could provide more details of what you are trying to citate? 

Thanks!

**Comment by data-gov-my** [comment]
We intentionally didn't do this, as there are already existing academic standards (APA, MLA, Chicago, etc) for how to cite a website.
