### ISSUE TITLE
How does filtering actually work?

### ISSUE THREAD

**Issue by hbina** [data-gov-my/datagovmy-front#440]
I can't get the births API to filter for the dates that I want. See,

```
(base) hbina@akarin:~/git/mygov$ curl --silent 'https://api.data.gov.my/data-catalogue/?id=births&date_start=2020-02-12@date' --compressed | jq '.[0]'
null
(base) hbina@akarin:~/git/mygov$ curl --silent 'https://api.data.gov.my/data-catalogue/?id=births' --compressed | jq '.[0]'
{
  "date": "1920-01-01",
  "state": "Malaysia",
  "births": 96
}
```

According to the [docs](https://developer.data.gov.my/request-query), I can specify a date filter using the `date_start` query. Since the JSON object have the `date` keyword, I assume that is the column name, so I specify the date by adding `date_start=2023-02-12@date` to filter for births after 2023-02-12. But it clearly does not work.

Please help.

**Comment by eujiaxin** [comment]
> I can't get the births API to filter for the dates that I want. See,
> 
> ```
> (base) hbina@akarin:~/git/mygov$ curl --silent 'https://api.data.gov.my/data-catalogue/?id=births&date_start=2020-02-12@date' --compressed | jq '.[0]'
> null
> (base) hbina@akarin:~/git/mygov$ curl --silent 'https://api.data.gov.my/data-catalogue/?id=births' --compressed | jq '.[0]'
> {
>   "date": "1920-01-01",
>   "state": "Malaysia",
>   "births": 96
> }
> ```
> 
> According to the [docs](https://developer.data.gov.my/request-query), I can specify a date filter using the `date_start` query. Since the JSON object have the `date` keyword, I assume that is the column name, so I specify the date by adding `date_start=2023-02-12@date` to filter for births after 2023-02-12. But it clearly does not work.
> 
> Please help.

The filter is working as expected, however the dataset for `births` in OpenAPI was previously using the partial dataset as shown in https://data.gov.my/data-catalogue/births, where the last birthday ends at 1921-01-01. We have amended OpenAPI to always return the full dataset, so your API request should return non-empty data now.

```
curl --location 'https://api.data.gov.my/data-catalogue?id=births&meta=true&date_start=2023-02-12@date'
```

Alternatively, you can also directly download the parquet/csv file linked in https://data.gov.my/data-catalogue/births
![image](https://github.com/data-gov-my/datagovmy-front/assets/42997224/c8524cd4-d9a6-44e9-b784-8bed95a5032f)
